Nick
JustinHoyt/poker pull request #1
Opened 2021-02-16 03:26 UTC by nwestallen

2021-02-17 02:37 UTC, JustinHoyt requested changes
We need a good eslint config that can enforce a good style. If we already have one, then in `npx eslint src` to see where the warnings and errors are. Try to set up your editor to integrate with our eslint config so it helps you as you code.

2021-02-17 02:37 UTC, JustinHoyt commented on .eslintcache
> +[{"/Users/nickallen/Documents/Dev/poker/src/index.tsx":"1","/Users/nickallen/Documents/Dev/poker/src/reportWebVitals.ts":"2","/Users/nickallen/Documents/Dev/poker/src/App.tsx":"3","/Users/nickallen/D
This file should be in the .gitignore file. We don’t want to track it.

2021-02-17 02:37 UTC, JustinHoyt commented on src/constants.tsx
> +const deck52 = [
This should be generated in a nested for loop.

we should also make an enumeration for the suits and another for the ranks so we can have more readable names when writing code or testing.

2021-02-17 02:37 UTC, JustinHoyt commented on src/App.tsx
> +  const [room, setRoom] = useState({users: {0:{}}, pot: 0, board:[{}], deck: deck52})
Type this with an interface

2021-02-17 02:37 UTC, JustinHoyt commented on src/App.tsx
> +      if(data) {setRoom({
You need a line break after the first curly brace

2021-02-17 02:37 UTC, JustinHoyt commented on src/App.tsx
> +      if(data) {setRoom({
We need eslint to be helping you out here.

2021-02-17 02:37 UTC, JustinHoyt commented on src/App.tsx
> +      let playerHand = `users.${position}.cards`
Use const whenever possible

2021-02-17 02:37 UTC, JustinHoyt commented on src/App.tsx
> +        {Object.keys(room.users).map(key => <Seat hand={room.users[key].cards} dealCard={() => dealCard(key)} clearHand={() => clearHand(key)} player={room.users[key]} />)}
Too much for one line. Make a line break after the opening paren for .map

use `Object.entries` to key both the key and value
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries

2021-02-17 02:37 UTC, JustinHoyt commented on src/components/Board.tsx
> +const Board = (props) => {
Make an interface for your props in all your functional components that take props in

2021-06-09 03:08 UTC, nwestallen commented
I'm going to start a fresh branch so I can implement things via cloud functions and have a more readable working tree

2021-06-09 03:08 UTC, closed without merging